# Quick-Spider Crawl Results
# Generated: 2025-12-28 13:48:52
# Target: https://vulnweb.com/
# Total discovered: 1
# Status: In progress

crawled = {
  "https://vulnweb.com/" = {
    depth = 0,
    parent = "",
    type = "[DIR]",
    links = []
  }

}
